ALTER TABLE student ADD CONSTRAINT where16 CHECK ( age > 16 ) ;

ALTER TABLE student ADD CONSTRAINT nameUniq UNIQUE (name) ;

ALTER TABLE student ALTER COLUMN name SET NOT NULL ;

ALTER TABLE faculty ADD CONSTRAINT colorUniq UNIQUE (name, color) ;

ALTER TABLE student ALTER COLUMN name SET DEFAULT 20 ;